---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: prometheus-nginx-exporter
  static_configs:
  - targets: ["localhost:9113"]
  metrics_path: /metrics
  scheme: http